alter session set current_schema=u_dw_references;
--drop table t_months;

Create table t_quarters (
QUARTER_ID                      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, 
DAYS_IN_CAL_QUARTER           NUMBER,
BEG_OF_CAL_QUARTER            DATE,
END_OF_CAL_QUARTER            DATE,
CALENDAR_QUARTER_NUMBER       VARCHAR2(1),
CONSTRAINT "PK_DW.T_QUARTER" PRIMARY KEY ( QUARTER_ID ) USING INDEX TABLESPACE ts_references_idx_01
);

SELECT * FROM t_quarters;