alter session set current_schema=u_dw_references;
--drop table t_months;

Create table t_months (
MONTH_ID                      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, 
CALENDAR_MONTH_NUMBER         VARCHAR2(2)  ,
DAYS_IN_CAL_MONTH             VARCHAR2(2)  ,
END_OF_CAL_MONTH              DATE         ,
CALENDAR_MONTH_NAME           VARCHAR2(32) ,
CONSTRAINT "PK_DW.T_MONTH" PRIMARY KEY ( MONTH_ID ) USING INDEX TABLESPACE ts_references_idx_01
)