
alter session set current_schema=DW_CLEANSING;
GRANT SELECT ON DW_CLEANSING.cl_customers TO DW_DATA;

alter session set current_schema=DW_DATA;

DROP SEQUENCE SEQ_CUSTOMERS;
CREATE SEQUENCE SEQ_CUSTOMERS
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE OR REPLACE PACKAGE body pkg_dw_customers
AS  
  PROCEDURE LOAD_DW_CUSTOMERS
   AS
     BEGIN
     MERGE INTO DW_DATA.dim_customers A
     USING ( SELECT FIRST_NAME_CUSTOMER, LAST_NAME_CUSTOMER,COUNTRY_CITY_CUSTOMER, ADRESS_CUSTOMER, EMAIL, PHONE_CUSTOMER, AGE,IS_ACTIVE, CUSTOMER_SALE_DATE
             FROM DW_CLEANSING.cl_customers) B
             ON (a.PHONE_CUSTOMER = b.PHONE_CUSTOMER)
             WHEN MATCHED THEN 
                UPDATE SET a.ADRESS_CUSTOMER = b.ADRESS_CUSTOMER
             WHEN NOT MATCHED THEN 
                INSERT (a.CUSTOMER_ID, a.FIRST_NAME_CUSTOMER, a.LAST_NAME_CUSTOMER,a.COUNTRY_CITY_CUSTOMER, a.ADRESS_CUSTOMER, a.EMAIL, a.PHONE_CUSTOMER, a.AGE,a.IS_ACTIVE, a.CUSTOMER_SALE_DATE)
                VALUES (SEQ_CUSTOMERS.NEXTVAL, b.FIRST_NAME_CUSTOMER, b.LAST_NAME_CUSTOMER,b.COUNTRY_CITY_CUSTOMER, b.ADRESS_CUSTOMER, b.EMAIL, b.PHONE_CUSTOMER, b.AGE, b.IS_ACTIVE, b.CUSTOMER_SALE_DATE);
     COMMIT;
   END LOAD_DW_CUSTOMERS;
END pkg_dw_customers;

alter session set current_schema=DW_DATA;
exec pkg_dw_customers.LOAD_DW_CUSTOMERS;
select * from dim_customers;

commit;