alter session set current_schema=u_dw_references;
--drop table t_months;

Create table t_years (
    YEAR_ID                      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, 
    DAYS_IN_CAL_YEAR NUMBER,     
    BEG_OF_CAL_YEAR DATE,      
    END_OF_CAL_YEAR DATE,
    CALENDAR_YEAR VARCHAR2(4),
CONSTRAINT "PK_DW.T_YEAR" PRIMARY KEY ( YEAR_ID ) USING INDEX TABLESPACE ts_references_idx_01
);

SELECT * FROM t_years;